auth-server: http://www.qixingshe.xyz:8010

security:
  oauth2:
    client:
      clientId: challenge1
      clientSecret: challengeSecret1
      scope: all
      user-authorization-uri: ${auth-server}/oauth/authorize
      access-token-uri: ${auth-server}/oauth/token
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
#      jwt:
#        key-uri: ${auth-server}/oauth/token_key
server:
  port: 8011
  servlet:
    context-path: /client1



