export const ADD_MENU="MENU/ADD";

export const TOGGLE_REMOVE_MENU='MENU/REMOVE/LOGIC'

export const RENAME_MENU="MENU/RENAME";

export const TOGGLE_FAVORITE='MENU/FAVORITE';

export const DELETE_MENU='MENU/DELETE';



