security:
  oauth2:
    client:
      clientId: challenge2
      clientSecret: challengeSecret2
      user-authorization-uri: http://www.qixingshe.xyz:8010/server/oauth/authorize
      access-token-uri: http://www.qixingshe.xyz:8010/server/oauth/token
    resource:
      jwt:
        key-uri: http://www.qixingshe.xyz:8010/server/oauth/token_key

spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://challenge-db:3306/challenge_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: challenge
    password: 123456
  redis:
    host: localhost
    port: 6379
    password:
server:
  port: 8012
  servlet:
    context-path: /client2

