server:
  port:
    8080
spring:
  application:
    name: challenge-demo
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://challenge-db:3306/challenge_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: challenge
    password: 123456
  redis:
    host: localhost
    port: 6379
    password:


challenge:
  security:
    code:
      imageCode:
        length: 4
    browser:
      loginPage: /auth-normal-signIn.html
      registerPage: /register.html
      loginType: REDIRECT
    social:
      qq:
        providerId: qq
        app-id: 101543475
        app-secret: 27534e32bca33b8cf9daa1db7149f7c7
    oauth2:
      clients[0]:
        clientId: challenge
        clientSecret: challengeSecret
        accessTokenValidateSeconds: 3600
      storeType: jwt
