auth-server: http://www.qixingshe.xyz:8010

#security:
#  oauth2:
#    client:
#      clientId: challenge1
#      clientSecret: challengeSecret1
#      user-authorization-uri: http://www.qixingshe.xyz:8010/server/oauth/authorize
#      access-token-uri: http://www.qixingshe.xyz:8010/server/oauth/token
#    resource:
#      jwt:
#        key-uri: http://www.qixingshe.xyz:8010/server/oauth/token_key
#      user-info-uri: http://www.qixingshe.xyz:8010/user




security:
  oauth2:
    client:
      client-id: a # 授权服务器配置的client id
      client-secret: a # 授权服务器配置的client secret
      scope: test
      access-token-uri: ${auth-server}/oauth/token # 获取access token接口
      user-authorization-uri: ${auth-server}/oauth/authorize #  获取Authorization Code接口
    resource:
      token-info-uri: ${auth-server}/oauth/check_token # 验证token的接口
#      user-info-uri: ${auth-server}/user # 一个可以获取认证授权的自定义接口，可以在授权服务器，也可以在其他服务器上
#      prefer-token-info: true # 如果同时配置了token-info-uri 和 user-info-uri，这个现象设置使用哪个取验证授权

server:
  port: 8011
  servlet:
    context-path: /client1
