server:
  port: 8010
  servlet:
    context-path: /server

spring:
  security:
    user:
      password: 123456
      name: admin
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://challenge-db:3306/challenge_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: challenge
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: