server:
  port: 8081

spring:
  application:
    name: grg-browser-demo

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://challenge:challenge@challenge-eureka:2010/eureka
